language: php
php:
  - '7.1'
before_install: 
  - echo "extension=apcu.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "apc.enabled=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "apc.enable_cli=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "date.timezone=Europe/Berlin" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
before_script: 
  - echo "Date:"
  - date
script: phpunit --bootstrap ./tests/lib/core/bootstrap.php --configuration ./tests/phpunit.dist.xml tests/
